name: Pull Request
on:
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Install Tools
        run: dotnet tool restore
      - name: Install Packages
        run: dotnet paket install
      - name: Test
        run: ./fake.sh Test
