name: Release
on:
  release:
    branches:
      - main
    types:
      - published
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore Tools
        run: dotnet tool restore
      - name: Install Packages
        run: dotnet paket install
      - name: Publish
        run: ./fake.sh Publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
